### ISSUE TITLE
각페이지 디자인 잡기

### ISSUE THREAD

**Issue by Mokdasoo** [reply-1995/FirtPrjGameWeb#1]
- [x] 메인 페이지 
- [x] 로그인 페이지
- [x] 회원가입 페이지
- [x] 회원정보수정 페이지
- [x] 게시판 페이지 - 자유게시판, 정보게시판
- [x] 랭킹 페이지
- [x]  FAQ
- [x] 게임가이드

**Comment by Seoyoung-Mun** [comment]
메인페이지
[메뉴탭] [로그인] [게임시작버튼] [게시글 노출]

메뉴탭
[뉴스] - 공지사항, 이벤트
[가이드]
[랭킹]
[커뮤니티] - 자유게시판, 정보게시판
[고객지원] - FAQ, 1:1문의

**Comment by Seoyoung-Mun** [comment]
0. 헤더 푸터
1. 로그인/회원가입, 회원정보 수정페이지
2. 게임페이지
3. 게시판 - 자유게시판, 정보게시판
4. 뉴스 - 공지사항, (이벤트)
5. 고객지원/가이드 - 가이드는 이미지캡쳐본...
6. 랭킹 - 명예의전당
7. 메인 페이지
8. 발표자료준비(ppt등)
